### ISSUE TITLE
Players can't use javascript macros

### ISSUE THREAD

**Issue by ctbritt** [League-of-Foundry-Developers/fvtt-advanced-macros#1]
Hi-- just installed, and this seems to break players' ability to use the macros on their hotbar. When it's enabled (and it's the only mod enabled), players see a yellow alert bar that says "You are not allowed to use Javascript macros." 

When module disabled, players can use the hotbar macros. (these are items dragged from the character sheet.) 

Players have permission to run macros in my user setup.

Running 0.8.5 in dnd5e 1.3.2.

**Comment by mclemente** [comment]
Oops, sorry about that, It's related to a change between 0.7.9 and 0.8. It's fixed now, thank you!
