### ISSUE TITLE
Installing the module installs an old version (1.6)

### ISSUE THREAD

**Issue by cs96and** [League-of-Foundry-Developers/fvtt-advanced-macros#16]
When you install the Advanced Macros module, it only installs v1.6.  Hitting the upgrade button then upgrades it to v1.9.

**Comment by kaelad02** [comment]
The module page on foundryvtt.com still shows 1.6 as the latest. Someone needs to go to the admin console and add a new entry for the latest version.

**Comment by mclemente** [comment]
This should be fixed now. The Foundry package wasn't owned by me, so I couldn't update it.
