### ISSUE TITLE
Return statements in non-async macros aren't working

### ISSUE THREAD

**Issue by itamarcu** [League-of-Foundry-Developers/fvtt-advanced-macros#17]
(Chrome, Foundry v0.8.9, Advanced Macros v1.9)

I have a very simple macro, named "test5":

```js
return "1234"
```

In the Foundry chat, when I type `/test5`, it doesn't do anything, when I would expect it to create a chat message saying 1234.
I'm pretty sure this is a bug in the module - it treats all macros as async even when they aren't.  This is maybe due to a change in Foundry 0.8.x that made all macros async by default.

When debugging, the code reaches [this line](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/blob/main/Macros.js#L309) and returns `""` instead of the content, since it always gets a promise.

**Comment by mclemente** [comment]
You can't make a Script macro to create a chat message like that, you'd need to call the whole ChatMessage.create().

**Comment by itamarcu** [comment]
No, I'm pretty sure this is a bug in the module, as return statements are supposed to work like that.

Look at one of the macros included in this module, for example: `current-time`.

```js
// Returns the current time in format "HH:MM" (24 hour format)
const now = new Date();
return `${now.getHours()}:${now.getMinutes()}`;
```

If you import this macro and then type `/current-time` in the chat box, nothing will happen (bug).

There's another macro included in the module: `Say hello`, which is a chat macro that uses `current-time`.

```js
Hi {{game.user.name}}, it is now {{macro "current-time"}}
```

If you import this macro and execute it, it will post in the chat:  `Hi Gamemaster, it is now`.  This again shows that `current-time`'s return value is the empty string `""` instead of the expected result.

The Readme states that it should allow such returns in non-async macros:
> In the case of script macros, you can now use a `return1 statement for the early return paradigm, but also to retun a string which can then be used in chat macros. You will also be able to receive arguments via an array named args, and you can use the `await` keyword to make your script asynchronous. Do note however that if you create an async macro, it cannot be used to return text in a chat macro when using the `{{macro}}` helper. It will still be executed if used, but will be considered to have returned an empty string. If you want to use an async macro that prints its results to chat, read further for the use of recursive async chat commands.

The problem is that, due to [this line](https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/blob/main/Macros.js#L177), ALL macros are now considered async macros. This is due to imitating the Foundry 0.8.x code that made all macros async by default.

The bug can be solved by removing the `async` keyword in the line I linked here, but then functions won't be async by default and won't be able to include `await` in their top level code.  So, I think the solution would need to be something weird like... first checking if the macro contains the `await` keyword in a top-level line and then only wrapping it with `async` if it does.  Or alternatively, have three different types of macros, `chat`/`script (sync)`/`script (async)`.  Maybe there's a cleverer way of running the code without async and checking if it returns a promise, but I think then it will log a warning which is bad.

**Comment by mclemente** [comment]
Sorry for the misunderstanding, it's fixed now.

**Comment by itamarcu** [comment]
Checking if `await` is inside the command should help, thanks!  This isn't a perfect fix because I can imagine some sync code might include async functions within it (called in the background), but this should probably handle most scenarios.

**Comment by mclemente** [comment]
That's how the Furnace did it, I removed it when it was split because of 0.8's changes and it didn't cross my mind that this would be an issue.
