### ISSUE TITLE
Conflicting with MrPrimate's Tokenizer

### ISSUE THREAD

**Issue by vtt-lair** [League-of-Foundry-Developers/fvtt-advanced-macros#20]
Your module currently ships with a library called tokenizer.min.js that is conflicting with MrPrimate's Tokenizer module.

I spoke to him quickly regarding this, as he has functionality linked to his Tokenizer module that allows macro's or other modules to call his functionality. The Tokenizer within tokenizer.min.js is causing a conflict with his module.

Asked that I open a ticket on your page to see if there's anything you can do, as he can't really change his Tokenizer class name.

**Comment by MrPrimate** [comment]
Note: I expose functions for tokenizer via window.Tokenizer and it seems that there is a conflict, presumably with the class loaded from the tokenizer library you're using.

**Comment by mclemente** [comment]
@vtt-lair Can you send me a macro to test the conflict? I can see why it might break, but I'm not sure how to reproduce the conflict.

**Comment by MrPrimate** [comment]
@vtt-lair I think a work around to call Tokenizer would be to call `window.Tokenizer.launch()` instead.

**Comment by vtt-lair** [comment]
@MrPrimate  and @mclemente, I can confirm that the ```window.Tokenizer.launch``` work around works.

@mclemente, you can use the following macro to replicate the issue:
```
let tokenizerOptions = {
  name: "test",
  avatarFilename: "uploads/example/example_avatar_image.png",
  targetFolder: "[data] uploads/tokens/special",
  usefulString: "Useful data"
};

Tokenizer.launch(tokenizerOptions, (response) => {console.log(response)});
```

Changing the ```Tokenizer.launch(tokenizerOptions, (response) => {console.log(response)});``` to ```window.Tokenizer.launch(tokenizerOptions, (response) => {console.log(response)});``` as per MrPrimate's comment will ignore Advanced Macro's library

**Comment by mclemente** [comment]
I see. Advanced Macros only calls for a `tokenizer` variable through the TokenizeThis() class, so I wasn't sure how to get the error.
I don't think I can fix this without messing with the library, which I won't do.

**Comment by mclemente** [comment]
This issue was fixed in the Tokenizer module. Closing this issue.
