### ISSUE TITLE
Visual problem in the macro sheet

### ISSUE THREAD

**Issue by GabrielOsvair** [League-of-Foundry-Developers/fvtt-advanced-macros#28]
Visual problem in the macro sheet when I activate the module. Clean world.

![image](https://user-images.githubusercontent.com/67530921/160972731-2f9cc774-628d-42af-a054-1061e8e761bc.png)

Foundry Virtual Tabletop: Version 9, 9.255
Game System: dnd5e, 1.5.7
Active Modules: 1
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1215)
Max Texture Size: 16384

Scene: 3000 x 3000 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 2

Actors: 89 | Items: 32 | Journal: 0 | Rollable Tables: 9 |
Playlists: 0 | Compendium Packs: 11 | Chat Messages: 0

**Comment by wickermoon** [comment]
I have a similar problem, where the text inside the Command editor is misaligned
![image](https://user-images.githubusercontent.com/15907070/182599909-4459041c-4be5-4e7e-84b7-b955a8bb6309.png)
