### ISSUE TITLE
getTemplateContext ignores input actor and token

### ISSUE THREAD

**Issue by toastygm** [League-of-Foundry-Developers/fvtt-advanced-macros#3]
In the standard `Macro.execute({actor, token}={})` method, it takes two parameters: the `actor` and `token`.  It sets these values in the invoked javascript function based on these input parameters if they are present.

However, `getTemplateContext()` always ignores these parameters, even if they are specified in `args` parameter.  Instead, it calculates them from the `speaker`.

`getTemplateContext()` needs to be modified to accept the input actor and token if they are present, and only calculate them from `speaker` if they are not present.

**Comment by mclemente** [comment]
I fixed the logic, but couldn't test it because I haven't any macros that do that exactly, so it should work fine, unless it has a remoteContext, which will override the actor/token called anyway.

**Comment by mclemente** [comment]
After further checking, this was technically fixed (as in, it should respect vanilla macros' args), but Furnace's `args` is being passed as an array instead of a dict, so there's some work to do.
