### ISSUE TITLE
Chat macro activation broken in pf1

### ISSUE THREAD

**Issue by folken88** [League-of-Foundry-Developers/fvtt-advanced-macros#30]
Works in starfinder, but no longer in pf1. They blame the module so I'm reporting it here, but their update broke this so?

I use dozens of macros, called by typing their /name in chat, to facilitate blind players controlling their characters. They're unable to play when adv-macros is down. 

The error in the console is:
"foundry.js:58074 Uncaught (in promise) Error: /per is not a valid chat message command.
[No packages detected]
    at ChatLog.processMessage (foundry.js:58074:40)
    at ChatLog._onChatKeyDown (foundry.js:58356:19)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)"

**Comment by mclemente** [comment]
I see the problem, both the system and the module try to patch the same core function (ChatLog.parse).

As of right now, the fix would be a bit weird: I'd have to write down the original function and then patch PF1's patch. It's doable, but it isn't ideal. I'll try to get the PF1 devs to change how they store the original function so Advanced Macros can patch it without conflicting with their own patching.

**Comment by mclemente** [comment]
Hello, could you try updating Advanced Macros to version 1.14.3 and check if it is working properly now?

**Comment by folken88** [comment]
IT IS WORKING. THANK YOU THANK YOU. Do you have a patreon? I'm a paid GM
and I typically only sub to artists but truly dude, THIS MOD is the only
mod that is required. I have blind players and ONLY YOUR MOD matters. I
write macros for every skill, spell, attack, and check my blind players
have so they can just type /per for perception, /mm for magic missile, etc.
Without your mod, they cannot control their characters. With your mod, the
blind players are not only equal to the sighted folks, they are then better
(bc blind people have amazing memories) than average players.

Thank you so very much for your work. It is SO appreciated.

-Toby

**Comment by mclemente** [comment]
Thank you, it warms my heart to read this! It never crossed my mind this brought accessibility for blind people.

I don't have a Patreon since my modules don't have constant updates or new features. I do have a Ko-fi for donations, though: https://ko-fi.com/mclemente

I'm closing this issue as resolved.

**Comment by mclemente** [comment]
Hello, I just updated Advanced Macros' chat messages to fix another issue that came up.
As far as I've tested, the changes didn't affect PF1 at all, but, if anything comes up on version 1.17, be sure to tell me.

**Comment by folken88** [comment]
Works great! Everything but saves rolls with skipdialogue and the cursor
stays in chat. I tested skills, spells, items, and saves.

Thank you so much for your work on this mod!

**Comment by mclemente** [comment]
Hello, just a heads up that the next release will change the chat command from `/[macro name]` to `/amacro [macro name]` to avoid potential conflicts with systems and other modules.

**Comment by folken88** [comment]
DOH Ok. That's a lot of updating, thank you! Is FVTT itself going to
support /macro calls now? I asked atropos for that ages ago so I could quit
pestering you, lol...

-T

**Comment by folken88** [comment]
Finally got to try pf1/v11 and macros appear to be completely broken. Is
there any plan to return the /blarb simple style of macro use via your mod
or others? Is it possible in v11?

**Comment by mclemente** [comment]
Have you updated Advanced Macros after upgrading to V11? The V10 version breaks on V11, so you need to update the module to its latest version.

V11 also introduced its own macro arguments, which is a bit different from what Advanced Macros used, so you might need to fix some macros.

With that said, the "/blarb" feature is still there, though.

**Comment by folken88** [comment]
Oof I'm so sorry I bothered you! I see you've put a check-box in the mod
config that gets my people where they need to be. Thank you for that, and
thank you for taking the time to help us as you have a dozen times already!

-T
