### ISSUE TITLE
Bounding box issues with latest update

### ISSUE THREAD

**Issue by westonsfiala** [League-of-Foundry-Developers/fvtt-advanced-macros#31]
After updating to the latest version of the module, the editor box of macros have bounding box issues. This is particularly annoying as the cursor does not line up with the text. The error image is from a world with no other modules installed.

![image](https://user-images.githubusercontent.com/35877665/175791748-c24e97b5-cba3-41e2-b173-c4afb40c48bf.png)
![image](https://user-images.githubusercontent.com/35877665/175791752-e4e6c063-ca95-4693-9632-7126a87f1014.png)

Advanced Macro - version 1.14.3

**Comment by mclemente** [comment]
Sorry to hear that. While I'm working on a fix, disable the Highlight Macro Codes setting to at least have the  editor work as normal.
