### ISSUE TITLE
Removing "invalid" from ChatLog message patterns can break Foundry behavior

### ISSUE THREAD

**Issue by gizmo2342** [League-of-Foundry-Developers/fvtt-advanced-macros#39]
Hi,
last week I was notified about broken 'inline roll command' buttons im my GameSystem under v10 that only occur if the advanced-macros add-on ist activated. And because the behaviour was really weird, I took a closer look and want to share my findings with you.

Since v10 I'm using the `TextEditor` enrichers API to do render inline commands (`[[/foo bar]]`). And here is the catch: `TextEditor#_createInlineRoll` also uses `ChatLog#parse` internally and relies on the "invalid" pattern (`foundry.js:56844`, Foundry v10.286) to work correctly. For non built-in inline commands this means to not touch them, so that registered enrichers can do their work. 

In addition I'm not sure if you really need to delete the pattern. I have custom chat commands myself and I handle them in the `chatMessage` Hook, and I had no problems with it so far.

https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/blob/1ee2b9c240d953b6c895e8c9e40a8292ae7e8889/Macros.js#L21

I hope this information is useful for you and you can find a way without deleting the 'invalid' pattern.

If you need more information, please contact me.

Greetings
Martin

PS: Maybe "none" (which is the parse result when "invalid" is removed) should also act like "invalid". Can't see why `_createInlineRoll` should want to continue without a valid match. I'll contact Foundry for this.

**Comment by mclemente** [comment]
Thanks for the input. I wasn't aware that there was a hook that was called before `preCreateChatMessage`. Newest version of the module should work without deleting `ChatLog.MESSAGE_PATTERNS`.
