### ISSUE TITLE
advanced macros 1.5.1 issue: actor and token are undefined.

### ISSUE THREAD

**Issue by Freeze021** [League-of-Foundry-Developers/fvtt-advanced-macros#4]
since the last update of advanced-macros the vars **token** and **actor** are now undefined. They are still predefined by foundry, they just return undefined. Scene and speaker appear to be untouched.
![test](https://user-images.githubusercontent.com/84507769/120464883-b5a98680-c39d-11eb-9921-605e97e700be.png)

**Comment by mclemente** [comment]
Sorry about that, I uploaded the wrong file, it should be fixed now.
