### ISSUE TITLE
Pass arguments to macro from within document

### ISSUE THREAD

**Issue by chligget** [League-of-Foundry-Developers/fvtt-advanced-macros#42]
Is it possible to pass arguments to a macro call from say within a Journal or Rollable table? I used to do it with module Dynamic Macro Links, but v10 has busted that for now.

ex. (Editing a Journal Entry) @UUID[Macro.macroID /arg1 "arg2"]{Macro Name}

**Comment by mclemente** [comment]
I can't promise anything until ProseMirror (the new Journal Editor) is easier for modding. So don't get your hopes up.

**Comment by mclemente** [comment]
It didn't require messing with the Journal Editor at all, so it was easier than I imagined, but I couldn't get it to work with Rollable Tables for now.

**Comment by chligget** [comment]
Thank you so much for this fix! It helps cut down the number of macros I need significantly! As far as Rollable Tables go, I figured out a work around:
 
Select the Result Type as "Text" (NOT Document > Macro). Then in the Result Details box, enter in your Advanced Macros format (  i.e. @UUID[Macro.ID foo bar]{Macro}    ) and voila, it works!

**Comment by Ed1013** [comment]
This is just what I needed! But I can't get it to work. So, in the journal entry I am entering @uuid[Macro.ID foo bar]{Macro} like @GL6XiFm1tLYm3v5u[argtest.aISMjgGkEtjiMJNA testing]{argtest} I'm sure I'm doing it wrong.

**Comment by BURG3R5** [comment]
Hey @mclemente can you share the exact syntax that will work? I'm on v14 and `@UUID[Macro.abcdefghij value]{Run}` is showing up as a broken link.

Edit: Nevermind; seems like this feature was removed in v2.3.0.
