### ISSUE TITLE
In v10, macro not called when using ChatMessage.create({content: "/macroName arg1 arg2"})

### ISSUE THREAD

**Issue by rikmarais** [League-of-Foundry-Developers/fvtt-advanced-macros#43]
Advanced Macros `v1.17.3`
FoundryVTT `10.288`

In v10, Advanced Macro does not catch chat messages created using `ChatMessage.create({content: "/macroName arg1 arg2"})` from macro/script or console.

This might be an issue with worlds that rely on [Trigger Happy](https://github.com/League-of-Foundry-Developers/fvtt-module-trigger-happy), or cases where people relied on macros/scripts that used `ChatMessage.create({content: "/macroName arg1 arg2"})` to use Advanced Macros to pass multiple arguments into their macros.

The chat message gets created as `/macroName arg1 arg2`, but Advanced Macros does not pick it up and does not call `macroName` with or without arguments.

**Comment by mclemente** [comment]
It should be fixed on the latest version of the module now.

**Comment by rikmarais** [comment]
Awesome, thank you!!
