### ISSUE TITLE
Macros command echoed to the Chat Log

### ISSUE THREAD

**Issue by trdischat** [League-of-Foundry-Developers/fvtt-advanced-macros#5]
When I invoke a macro from chat using a command like this `/MacroName 5 3` the command is echoed to the chat log.  When I do this with The Furnace in FVTT 0.6.6, the same command does not show in the chat log.  Is there any way to prevent the macro command from echoing to the chat log?

**Comment by trdischat** [comment]
I assume it was on purpose, but commenting out the line for chat commands disables that function completely, which cripples certain functions of other modules, like Trigger Happy, that rely on this function.

**Comment by mclemente** [comment]
Yes, I've disabled it for now because there is also another issue (https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/issues/7) where the module is checking other /commands.

**Comment by mclemente** [comment]
Ok, found the issue. It was the `async` in `async preCreateChatMessage()`.
